In [38]:
from PIL import Image
import cv2
import numpy as np
import torch
import torchvision.transforms.functional as FT

In [39]:
img_path = '/home/mathurin/prudence/data_no_fusion/Serie_6/Thermique/thermal3.png'

## PILLOW

In [40]:
image = Image.open(img_path, mode='r')
print(image.mode)

I


In [46]:
#converting to tensor
image_tensor = FT.to_tensor(image).type(torch.FloatTensor)
print(image_tensor.std())
print(image_tensor.mean())

tensor(196.8579)
tensor(29148.3340)


In [24]:
# converting to numpy array
image_array = np.array(image).astype('uint16')
print(image_array.dtype)
print(image_array)

uint16
[[29106 29104 29108 ... 29161 29163 29176]
 [29104 29074 29106 ... 29153 29165 29180]
 [29085 29089 29098 ... 29174 29165 29190]
 ...
 [29599 29284 29127 ... 29110 29096 29115]
 [30100 29392 29148 ... 29098 29110 29113]
 [30161 29392 29130 ... 29117 29138 29134]]


In [25]:
# back to PIL image
image_2 = Image.fromarray(image_array)
print(image_2.mode)

I;16


## OPENCV

In [31]:
image = cv2.imread(img_path, -1)
print(image.dtype)
print(image)

uint16
[[29106 29104 29108 ... 29161 29163 29176]
 [29104 29074 29106 ... 29153 29165 29180]
 [29085 29089 29098 ... 29174 29165 29190]
 ...
 [29599 29284 29127 ... 29110 29096 29115]
 [30100 29392 29148 ... 29098 29110 29113]
 [30161 29392 29130 ... 29117 29138 29134]]
